# Numpy/Python Review I


### Python

Easy to pick, programmer-friendly language. 

"Python is an interpreted language, which can save you considerable time during program development because no compilation and linking is necessary. The interpreter can be used interactively, which makes it easy to experiment with features of the language, to write throw-away programs, or to test functions during bottom-up program development. It is also a handy desk calculator." -  [Python Tutorial](https://docs.python.org/3/tutorial/appetite.html)


Basics:
* Coming from C/C++? Use indentations for code blocks instead of braces. 
* Python is dynamically typed, no need to declare variables along with their data types.
* Python is interpretable, and code can be excuted line-by-line - use this to debug!


Tips:
* [Python reference docs](https://docs.python.org/3/reference/index.html) are great! Official documentation is your best friend.
* Python tutorial available on [course webpage](http://vision.stanford.edu/teaching/cs131_fall2223/).


References:
1. [Wikipedia](https://en.wikipedia.org/wiki/Python_(programming_language))
2. [Official Python Tutorial](https://docs.python.org/3/tutorial/index.html)


In [ ]:
## help?

help(print)
# help(range)
# help(len)


In [ ]:
import numpy as np
help(np)

### Numpy

**So you want to learn about numpy?**

Numpy is an important library for anyone wanting to work with large scale datasets in Python.  Numpy arrays provide value because they are easier and faster to manipulate than traditional python lists.

### Why use numpy arrays instead of Python lists?

1. Saves you time as a programmer: when using lists, you have to use loops to apply a function to each element of an array.  In numpy, all common mathematical computations can be vectorized.  This leads to a much faster runtime, as well as fewer lines of code. 

2. Under the hood, numpy arrays use less memory, and are constrained to a single data type, which enables faster execution.

### Contents
1. Array initialization and basic properties
3. Element wise matrix operations
4. Axis based matrix operations

### Let's get started!

In [ ]:
#It's a common convention to abbreviate numpy as np
import numpy as np

### Creating a Numpy Array
There are many ways to create a numpy array.  In general, the options are 
- converting other Python data structures to np.array format
- numpy functions that create new arrays (i.e. np.ones, np.zeros, np.arange)
- reading files from disk (in this class, mostly images)

Note that unlike lists, you can't create an empty numpy array

In [ ]:
# create a 1 dimensional array from a list: [1,2,3,4,5]
print("1 dimensional: ")
x = np.array([1,2,3,4,5])
print("Shape: ", x.shape)
x

In [ ]:
# Create a 2-d array from multiple lists: 
    # first row = [1,2,3,4,5]
    # second row = [6,7,8,9,10]
print("2 dimensional: ")
y = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("Shape: ", y.shape)
y

In [ ]:
# you can create an array of any dimensions using np.zeros
z = np.zeros((3,3))
z

In [ ]:
#other handy things
identity = np.identity(3) # also np.eye()
print(identity)

ones = np.ones((2,2))
print(ones)

ran=np.random.random((2,2))
print(ran)

In [ ]:
m=np.arange(10, 30, 5)#[min, max), step
print(m)

n=np.linspace(10, 30, 5)#min, max, num
print(n)

In [ ]:
print(m.dtype)
print(n.dtype)

### Array attributes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Take a look at the attributes associated with a numpy array, and then we'll explore how numpy arrays determine their type.

In [ ]:
print('shape:',identity.shape) #returns tuple of dimensions
print('size:',identity.size) # returns total number of elements
print('dtype:',identity.dtype) #the default dtype is float64
print('ndim:',identity.ndim) #returns number of dimensions

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

### Accessing elements

Numpy offers several ways to index into arrays. When arrays are one dimensional, indexing works just like lists. When arrays are 2 or more dimensional, you specify an index for each dimension:

`value = array[row_index, col_index]`

In [ ]:
# Create a 2-dimensional array (matrix)
# [[ 1  2  3]
#  [ 4  5  6]]
a = np.array([[1,2,3],[4,5,6]])   
print(a)

# Access the 3 with array indexing
a_3 = a[0,2]
print("expecting 3, got: ", a_3)

# Access the 4 with array indexing
a_4 = a[1,0]
print("expecting 4, got: ", a_4)

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array. Recall how slicing works in lists:

In [ ]:
# Recall list slicing:
l = [0,1,2,3,4]

print(l)
print("All elements of l: ", l[:])
print("All after 2nd element: ", l[2:])
print("All before 2nd element: ", l[:2])
print("All between 1st and 3rd element exclusive: ", l[1:3])

Now let's try slicing in two dimensions!

In [ ]:
print(a)

In [ ]:
print("a = \n", a)

# Access the 0th row of a:
a_row0 = a[0]
print("0th row expecting [1,2,3], got: ", a_row0)

# Access the 0th column of a
a_col0 = a[:, 0]
print("0th column expecting [1,4], got: ", a_col0)

Exercise:

In [ ]:
# TODO: Create the following rank 2 array with shape (4, 4)
# [[ 1,  2,  3,  4]
#  [ 5,  6,  7,  8]
#  [ 9, 10, 11, 12]
#  [13, 14, 15, 16]]

# HINT: if you want to take a fancy shortcut, use np.arange() to create this matrix

b = [[ 1,  2,  3,  4], 
     [ 5,  6,  7,  8], 
     [ 9, 10, 11, 12], 
     [13, 14, 15, 16]]
b=
print(b)

In [ ]:
# TODO: use slicing to pull out the middle two rows
b_rows = 
print("middle two rows: \n", b_rows)

# TODO: use slicing to pull out the middle two columns
b_cols = 
print("middle two columns: \n", b_cols)

# TODO: use slicing to pull out only the middle two rows and middle two columns,
# meaning a (2,2) array: 
# [[6 7]
#  [10 11]]
b_center = 
print("center two columns and two rows: \n", b_center)


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [ ]:
# [[ 1  2  3]
#  [ 4  5  6]]
a = np.array([[1,2,3],[4,5,6]])
print("original a = \n", a)

a_row0 = a[0,:]
a_row0[1] = 100 # a_row0[1] is the same piece of data as a[0, 1]

print("new a = \n", a)


### Part 2: Matrix Operations
Numpy makes it easy to do matrix operations on arrays, like multiply, invert, etc. Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print("x = \n", x)
print(x.dtype)
print("y = \n", y)
print(y.dtype)



In [ ]:
#all arithmetic operations are applied to a matrix element-wise
print("Original x: ")
print(x)
print("\nx+1")
print(x + 1)
print("\nx*4.5")
print(4.5*x)
print("\nx/2.0")
print(x/2.0)

In [ ]:
# Elementwise sum; both produce the array
print("x = \n", x)
print("y = \n", y)
print("\nx+y:")
print(x + y)
print(np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
print("x = \n", x)
print("y = \n", y)
print("\nx-y:")
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print("x = \n", x)
print("y = \n", y)
print("\nx*y:")
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print("x = \n", x)
print("y = \n", y)
print("\nx/y:")
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print("x = \n", x)
print("\nsqrt(x):")
print(np.sqrt(x))

In [ ]:
# Elementwise power; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print("x = \n", x)
print("\nx^2:")
print(np.power(x,2))

Exercise:

Let's practice these operations!

Given arrays x and y, write array z as a function of x and y: z[0] = x[0] - y[0], and z[1] = x[1] - y[1]. Use numpy operations!

Hint: think about how the 2 equations may be written with vector operations (such as those above), and that will translate cleanly to numpy 

In [ ]:
# TODO
x = np.array([1,3])
y = np.array([2,5])
z = np.array([-1,-2])

z_computed = 
print("Your answer: ", z_computed)
print("Expecting: ", z)
if z.all() == z_computed.all():
    print("Correct!")
else:
    print("Try thinking of a numpy function above with x and y that gets you equivalent to z")

Now, try using the numpy functions to calculate x = ((a+b)*c) - d

If you get stuck, try following the order of operations with the parenthesis and compute a+b first and verify by hand, and then proceed to (a+b)*c, and so on.

In [ ]:

a = np.array([1,3])
b = np.array([1,1])
c = np.array([2,1/2])
d = np.array([1,1])
x = np.array([3,1])

# TODO
answer =

print("Your answer: ", answer)
print("Expecting: ", x)
if x.all() == answer.all():
    print("Correct!")
else:
    print("Try thinking of a which numpy functions above with a,b, and c gets you equivalent to x")

# Part 3: Axis-based operations

Now that we've covered 2d indexing, there's some important numpy functions that operate on a particular axis, so let's get hands on with sum()! Many numpy operations including sum, max, argmax, mean, standard deviation operate over a chosen axis of your array. 

Sum can sum all elements of the 2d array, or it can sum across each row, or sum down each column. 

Axis 0 corresponds to columns, and axis 1 corresponds to rows, just like indexing. When you apply an operation like sum over axis 0, that means axis 0 is being squashed into length 1 by the sum, max, etc. operation.

In [ ]:
#numpy arrays have builtin methods to calculate summary statistics such as std. dev., mean, min, max, sum
y = np.random.random(9).reshape(3,3)
print(y)
print("std:", y.std())
print("mean:", y.mean())
print("sum:", y.sum())

print()
#you can also do these operations with respect to a particular axis
print("std (rows):", y.std(axis = 1))
print("mean (rows):", y.mean(axis = 1))

In [ ]:
# Sum of an array along various axes
x = np.array([[1,2],[3,4]])
print(x)
print()
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1)) # Compute sum of each row; prints "[3 7]"

Exercise:
Your turn!

In [ ]:
# Get hands-on with sum! Guess what the output will be and then run it to confirm
x = np.array([[1,2,3],[4,5,6],[3,2,1]])
print("x = \n", x)


In [ ]:

# TODO:
guess = 
print("Your guess for np.sum(x): ", guess)
print("Actual = ", 27)

In [ ]:
# TODO:
guess = 
print("Your guess for np.sum(x, axis=1): ", guess)
print("Actual = ", np.array([6,15,6]))

In [ ]:
# TODO:
guess =
print("Your guess for np.sum(x, axis=0): ", guess)
print("Actual = ", np.sum(x, axis=0))


Imagine I want to apply the function $f(x) = x^2 + x -6$ to every emelent of an array

In [ ]:
#First let's try it with python lists
import random
random.seed(1)
h = 1000000

def func(x):
    return x**2 + x - 6

first_list = [random.randint(-10,10) for i in range(h)]
print(len(first_list))

In [ ]:
%%time
for i in range(h):
        first_list[i] = func(first_list[i])

### Now let's do the same thing with numpy arrays

In [ ]:
#By default, rand returns a rnadom number in the range [0,1) - so we normalize to get the values we want
array = np.random.rand(h)
array = array*20 - 10
array = array.astype(np.int64)

In [ ]:
%%time
array = array**2 + array - 6

### It's way faster!

### Some other useful manipulations
A complete list of possible array manipulations can be found here:
https://numpy.org/devdocs/reference/routines.array-manipulation.html

In [ ]:
print(x)
print(y)
np.concatenate((x,y), axis = 0)

In [ ]:
result = np.concatenate((x,y), axis = 1)
result

In [ ]:
#not an inplace operation, if you want it to persist you need to reassign the variable using =
np.transpose(result)

In [ ]:
#to invert a matrix use np.linalg.inv
x = np.array([[1,1], [1,0]])
print(x)
np.linalg.inv(x)

### Numpy for Linear Algebra

#### Dot products

We'll first define vectors v and w. Recall that the dot product of two vectors is calculating by multiplying each corresponding value and then summing the result. Let's start by computing the dot product with a for loop

Exercise

In [ ]:
v = np.array([1,2,3])
w = np.array([4,5,6])

print("v = \n", v)
print("w = \n", w)
print("expected dot product = 32")

forloop_dotproduct = 0

# TODO: compute dot product of v and w with a for loop
# note: length of a 1 dimensional array  = len(array) or array.shape[0]


print(forloop_dotproduct)



In [ ]:
# TODO: compute dot product of v and w with numpy functions 
# hint: addition and summation are the key operations in a dot product

np_dotproduct = 
print(np_dotproduct)


#### Matrix-vector product

We'll first define matrix M and vector v. Recall that matrix multiplication between a matrix and a vector involves computing a dot product between each row of the matrix M and the vector v. 

In machine learning, M is typically a matrix of learned parameters where each row corresponds to one of the output predictions, which is a weighted sum of the input features from v. The features v change for every new example but the weights M are applied to every example in training and testing data.



In [ ]:
M = np.array([[1,2,3],[3,2,1]])
v = np.array([4,1,2])

print("M = \n", M)
print("v = \n", v)
print("Result = \n[12, 16]")

In [ ]:
# TODO: get each row of M using array slicing
M_row0 = 
M_row1 = 

# TODO: compute the dot product of each row of M with v
row0_dotproduct = 
row1_dotproduct = 

answer = np.array([row0_dotproduct, row1_dotproduct])
print("np.dot matrix product = \n", answer)

#### Matrix-Matrix multiplication

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[4,3],[2,1]])

print("A = \n", A)
print("B = \n", B)

In [ ]:
upper_left = 
print("upper left = ", upper_left)

upper_right = 
print("upper right = ", upper_right)

lower_left = 
print("lower left = ", lower_left)

lower_right = 
print("lower right = ", lower_right)

In [ ]:
# Numpy matrix products:
A = np.array([[1,2],[3,4]])
B = np.array([[4,3],[2,1]])
print(np.dot(A,B))
print(np.matmul(A,B))

### Broadcasting
The term broadcasting refers to how numpy treats doing arithmetic operations on arrays of different shapes.
When operating on two arrays, NumPy compares their shapes element-wise. Two dimensions are compatible when
* they are equal, or
* one of them is 1

If the dimensional are different, but one of them is 1, then numpy will apply the operation to each column on that axis

In [ ]:
x = np.array(range(5))
x = x.reshape(5, 1)
print("x is a column vector")
print()
print(x.shape)
print(x)

y = np.ones((5))
print("y is a row vector")
print(y.shape)
print(y)

In [ ]:
print(x+y)

### Real world example of why broadcasting is useful

In [ ]:
# Suppose we have a matrix where we want to normalize the rows to have mean zero
matrix = 10*np.random.rand(4,5)
matrix

In [ ]:
row_means = matrix.mean(axis = 1).reshape((4,1))
row_means

In [ ]:
matrix = matrix - row_means
print(matrix)
matrix.mean(axis = 1)

### Using boolean masks
In numpy, when you compare two arrays, you get a boolean mask as the output.  You can then use this boolean mask to grab specific values in an array.

In [ ]:
array = np.array(range(20)).reshape((4,5))
output = array > 10
output

In [ ]:
array[output]

In [ ]:
#you can combine boolean statements for more complicated operations
mask = (array < 5) | (array > 15)
mask

## Practice boolean mask problem
Given a matrix, change all of the negative values to zero

In [ ]:
matrix = 2*np.random.rand(5, 5) - 1
print(matrix)

In [ ]:
### SOLUTION ###
mask = matrix < 0
print(mask)
matrix[mask] = 0
print(matrix)

# Making Plots in Jupyter Notebook
A Matplotlib figure can be categorized into several parts as below:
    
**Figure:** It is a whole figure which may contain one or more than one axes (plots). You can think of a Figure as a canvas which contains plots.

**Axes:** It is what we generally think of as a plot. A Figure can contain many Axes. It contains two or three (in the case of 3D) Axis objects. Each Axes has a title, an x-label and a y-label.

**Axis:** They are the number line like objects and take care of generating the graph limits.

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x = np.arange(10)**2
print(x)
plt.plot(x)
plt.show()

In [ ]:
y=np.arange(10)+1
plt.figure(figsize = (5,5))
plt.plot(x,color='g',linestyle='dotted', marker='o',linewidth=5, label='a')
plt.plot(y,color='b',linestyle='dashdot', linewidth=8, label='b')
plt.title("This is a graph")
plt.xlabel("this is the x label")
plt.ylabel("this is the y label")
plt.annotate('this is the annotation', xy=(2,5), xytext=(2, 10),
            arrowprops=dict(facecolor='black', shrink=0.01),
            )
plt.legend()
plt.show()
plt.close()

In [ ]:
x=np.arange(10)
y=x*2
plt.scatter(x,y)
plt.show()
plt.close()

In [ ]:
plt.bar(x,y)
for i,j in zip(x,y):
    plt.text(i,j,j,ha='center', va='top')
plt.show()
plt.close()

### load the image

In [ ]:
import matplotlib.pyplot as plt
from skimage import io
def display(img):
    # Show image
    plt.figure(figsize = (5,5))
    plt.imshow(img)
    plt.axis('off')
    plt.show()
    
def load(image_path):
    out = io.imread(image_path)
    # Let's convert the image to be between the correct range.
    out = out.astype(np.float64) / 255
    return out

In [ ]:
img = load('image1.jpg')
display(img)

# Part 2

### Data Structures in Python
You may have noticed that it can be tricky to manipulate arrays in python because by default, python passed objects as references. In this section, we'll explain this behavior, and giving some debugging tools to use when confronted with related issues.

In [ ]:
array = np.linspace(1, 10, 10)
array

In [ ]:
dup = array
dup

In [ ]:
array[0] = 100
dup

In [ ]:
help(id)

In [ ]:
print(id(array))
print(id(dup))

### Notice that the dup and array point to the same object!
How would we fix this?

### Use the copy library, or np.array.copy
IMPORTANT: Using the slicing syntax [:] doesn't always work

In [ ]:
#slicing
array = np.linspace(1, 10, 10)
dup = array[:]
print(id(array))
print(id(dup))
a=[1,2,3,4,5]
b=a[1:2]
print()
print(id(a))
print(id(b))
array[0] = 100
print(dup)
b[0]=100
print(a)

In [ ]:
#using copy
import copy
array = np.linspace(1, 10, 10)
dup = copy.deepcopy(array)
print(id(array))
print(id(dup))
array[0] = 100
dup

Beware of copy vs. deepcopy!

https://docs.python.org/3.6/library/copy.html
<img src="shallow_copy.png">
<img src="deep_copy.png">

In [ ]:
#numpy arrays also have a builtin copy function
array = np.linspace(1, 10, 10)
dup = array.copy()
print(id(array))
print(id(dup))
array[0] = 100
dup

### Additional Resources
https://www.youtube.com/watch?v=8Mpc9ukltVA

https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html

https://towardsdatascience.com/matplotlib-tutorial-learn-basics-of-pythons-powerful-plotting-library-b5d1b8f67596

https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html

https://www.geeksforgeeks.org/copy-python-deep-copy-shallow-copy/